### ISSUE TITLE
Unable to use SCSS variable inside calc()

### ISSUE THREAD

**Issue by CroogQT** [CroogQT/karimkhalil.com#1]
Unable to use SCSS varaible $navHeight inside calc(). 

The specific context is:

```SCSS
$navHeight=5em;

//...

.navItems{

   // ...

    @include breakpoint('mobileNav'){

       // ...
        transform: translateY(calc(-100% - $navHeight));

    }

}
```

Hard coding 5em for now until I have a moment to figure this out.
